application:
  home: TASK_MANAGER

server:
  port: 8080

spring:
  datasource:
    driver-class-name:  org.postgresql.Driver
    url: jdbc:postgresql://localhost:3308/task_manager
    username: shikhar
    password: admin
    host: localhost
    port: 3308
    db-name: task_manager

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect